name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-macos:
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Cache Homebrew packages
    - name: Cache Homebrew packages
      uses: actions/cache@v3
      id: cache-brew
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-brew-llvm-${{ hashFiles('.github/workflows/ci_mac.yml') }}
        restore-keys: |
          ${{ runner.os }}-brew-llvm-

    - name: Install LLVM via Homebrew
      run: |
        brew update
        brew install llvm
        echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH

    # Install Poetry using the snok action
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: false

    # Cache Poetry dependencies
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ~/Library/Caches/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        poetry env use python3.12
        poetry install

    - name: Run Tests
      run: |
        poetry run pytest tests -v 